export const colorTokenNames = [
  "vivi-color-surface-canvas",
  "vivi-color-surface-panel",
  "vivi-color-surface-panel-raised",
  "vivi-color-surface-code",
  "vivi-color-surface-chrome",
  "vivi-color-surface-palette",
  "vivi-color-content-primary",
  "vivi-color-content-muted",
  "vivi-color-content-subtle",
  "vivi-color-content-on-accent",
  "vivi-color-border-default",
  "vivi-color-border-soft",
  "vivi-color-brand-primary",
  "vivi-color-brand-secondary",
  "vivi-color-brand-glow",
  "vivi-color-accent",
  "vivi-color-accent-gradient-end",
  "vivi-color-accent-surface",
  "vivi-color-accent-surface-subtle",
  "vivi-color-accent-border",
  "vivi-color-accent-strong",
  "vivi-color-accent-glow",
  "vivi-color-selection-surface",
  "vivi-color-selection-surface-subtle",
  "vivi-color-selection-border",
  "vivi-color-selection-indicator",
  "vivi-color-selection-text",
  "vivi-color-focus-ring",
  "vivi-color-focus-shadow",
  "vivi-color-change-text",
  "vivi-color-change-surface",
  "vivi-color-change-surface-muted",
  "vivi-color-change-surface-strong",
  "vivi-color-change-border",
  "vivi-color-warning",
  "vivi-color-warning-border-subtle",
  "vivi-color-warning-border",
  "vivi-color-warning-surface",
  "vivi-color-warning-surface-muted",
  "vivi-color-warning-surface-strong",
  "vivi-color-danger",
  "vivi-color-success",
  "vivi-color-success-text",
  "vivi-color-success-surface",
  "vivi-color-success-border",
  "vivi-color-diff-add",
  "vivi-color-diff-remove",
  "vivi-color-diff-add-line",
  "vivi-color-diff-remove-line",
  "vivi-color-json-string",
  "vivi-color-json-number",
  "vivi-color-json-boolean",
  "vivi-color-comment-surface",
  "vivi-color-comment-surface-active",
  "vivi-color-comment-border",
  "vivi-color-comment-text",
  "vivi-color-review-surface",
  "vivi-color-review-surface-active",
  "vivi-color-review-border",
  "vivi-color-review-text",
  "vivi-color-overlay",
  "vivi-color-shadow",
] as const;

export type ColorTokenName = (typeof colorTokenNames)[number];

export function colorTokenVar(name: ColorTokenName): string {
  return `var(--${name})`;
}
